controller:
  serviceType: NodePort
  persistence:
    enabled: true
    storageClass: minikube-hostpath
    size: 8Gi
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  startupProbe:
    initialDelaySeconds: 60  # Poczekaj 1 minutę zanim zaczniesz sprawdzać
    periodSeconds: 10        # Sprawdzaj co 10 sekund
    failureThreshold: 30     # Daj mu 30 szans (czyli 30 * 10s = 300s = 5 minut na start)
  JCasC:
    enabled: true
    configScripts:
      jenkins-casc: |
        jenkins:
          systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"
          
        jobs:
          - script: |
              freestyleJob('hello-world') {
                displayName('Hello World Job')
                description('Simple freestyle job that writes Hello World to logs')
                
                steps {
                  shell('echo "Hello World from Jenkins!"')
                }
              } 